# Generated by Django 2.0 on 2018-01-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_platform'),
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
