# Generated by Django 2.0 on 2017-12-30 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import games.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameListing',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('Complete In Box', (('cibvgood', 'Very Good'), ('cibgood', 'Good'), ('cibacceptable', 'Acceptable'))), ('Loose', (('loosevgood', 'Very Good'), ('loosegood', 'Good'), ('looseacceptable', 'Acceptable')))], max_length=32)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameListingImage',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=games.utils.gamelisting_image_upload)),
                ('gamelisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameListing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamelisting',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AddField(
            model_name='gamelisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
