# Generated by Django 2.0 on 2018-01-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20171230_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
    ]
