# Generated by Django 2.0 on 2018-01-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
        ('games', '0003_remove_game_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='platforms.Platform'),
            preserve_default=False,
        ),
    ]
