# Generated by Django 2.0 on 2018-02-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_platform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
